name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for trusted publishing
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install build twine
      - name: Clean previous builds
        run: |
          rm -rf dist/ build/ *.egg-info/
      - name: Build package
        run: |
          python -m build --sdist --wheel --outdir dist/
      - name: Check package metadata
        run: |
          python -m twine check dist/*
          ls -la dist/
      - name: Display wheel metadata
        run: |
          python -c "
          import zipfile
          import os
          for f in os.listdir('dist'):
              if f.endswith('.whl'):
                  print(f'Checking {f}')
                  with zipfile.ZipFile(f'dist/{f}', 'r') as z:
                      for name in z.namelist():
                          if 'METADATA' in name:
                              print(f'Found metadata file: {name}')
                              with z.open(name) as metadata:
                                  content = metadata.read().decode('utf-8')
                                  lines = content.split('\n')[:20]  # First 20 lines
                                  print('\n'.join(lines))
                              break
          "
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.2